// src/routes/about.tsx
import imageUrl from "@/assets/images/cover.jpg";
import { Anchor } from "@/components/Anchor";
import { Picture } from "@/components/Picture";
import { Group } from "@/components/atoms/Group";
import {
  Container,
  Paragraph,
  Section,
  imageWrapperStyle,
} from "@/styles/routes/about.styled";
import { createFileRoute } from "@tanstack/react-router";
import { AnimatePresence } from "framer-motion";
import { createRef, useEffect, useRef, useState } from "react";

export const Route = createFileRoute("/about")({
  component: About,
});

const paragraphs = [
  {
    id: 0,
    value: (
      <Group direction="column" align="center">
        <Group align="center">
          <Picture
            src={imageUrl}
            alt="Picture of Me"
            style={imageWrapperStyle}
          />
          <p>
            From Ireland and currently based in{" "}
            <span className="underline">Barcelona, Spain.</span> I'm a developer
            that enjoys developing with React.js, Typescript, and Python. My
            world revolves around electronic music, movies, rugby, and
            travelling.
          </p>
        </Group>
      </Group>
    ),
  },
  {
    id: 2,
    value: `I studied Computer Applications in DCU and started working with Jaguar Land
    Rover, Shannon in 2021 where I learned to work with REST APIs using Spring
    Boot and React.js early on. I'm currently working with a startup in the
    heart of Barcelona, TalentBait, as a frontend developer using React.js.`,
  },
  {
    id: 3,
    value: `I'm passionate about films, and I love sharing and keeping track of them on
    Letterboxd (the best social media platform).`,
  },
  {
    id: 4,
    value: `I've played sports all my life including Gaelic Football for Clontibret
    O'Neills GFC and rugby for teams like Ulster Club u18s, Monaghan RFC, Ennis
    RFC, and Corinthians RFC. More recently I've joined a local running club and
    I'm preparing for the Barcelona half marathon!`,
  },
  {
    id: 5,
    value: (
      <>
        I co-created{" "}
        <Anchor
          variant="link"
          text="Plant Bass'd"
          link="/blog/what-is-plant-bassd"
        />
        , an electronic music blog and underground club night that that took
        hold in Ireland and Scotland. Music is definitely a large part of my
        identity and I'm always trying my hand at producing music on Ableton.
      </>
    ),
  },
];

function About() {
  const [activeIndex, setActiveIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const sectionRefs = useRef<Array<React.RefObject<HTMLDivElement>>>(
    paragraphs.map(() => createRef<HTMLDivElement>())
  );

  useEffect(() => {
    const handleScroll = () => {
      if (!containerRef.current) return;

      const containerTop = containerRef.current.offsetTop;
      const scrollPosition = window.scrollY - containerTop;
      const windowHeight = window.innerHeight;

      const newIndex = Math.round(scrollPosition / windowHeight);
      if (
        newIndex !== activeIndex &&
        newIndex >= 0 &&
        newIndex < paragraphs.length
      ) {
        setActiveIndex(newIndex);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [activeIndex]);

  return (
    <Container ref={containerRef}>
      <AnimatePresence>
        {paragraphs.map(({ id, value }, index) => (
          <Section
            key={id}
            ref={sectionRefs.current[index]}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
          >
            <Paragraph>{value}</Paragraph>
          </Section>
        ))}
      </AnimatePresence>
    </Container>
  );
}

// pages/about.vue
<script setup lang="ts">
import imageUrl from "/images/cover.jpg";

useHead({
  title: "About Me",
});
</script>

<template>
  <main>
    <div class="container">
      <div class="paragraph">
        <p>
          Born in Ireland and currently based in
          <span class="underline">Barcelona, Spain.</span>
        </p>
        <p>
          I studied Computer Applications in DCU and started working with Jaguar
          Land Rover, Shannon in 2021 where I learned to work with REST APIs
          using Spring Boot and React.js early on.
        </p>
        <p>
          I'm passionate about films, and I love sharing and keeping track of
          them on Letterboxd (the best social media platform).
        </p>
        <p>
          I've played sports all my life including Gaelic Football for
          Clontibret O'Neills GFC and rugby for teams like Ulster Club u18s,
          Monaghan RFC, Ennis RFC, and Corinthians RFC. More recently I've
          joined Barcelona Gaels and a local running club!
        </p>
        <p>
          I co-created Plant Bass'd, an electronic music blog and underground
          club night. Music is definitely a large part of my identity and I love
          trying to make music in Ableton too!
          <PrettyLink
            text="What is Plant Bass'd?"
            link="/blog/what-is-plant-bassd"
          />
        </p>
      </div>
      <div class="image">
        <NuxtImg
          :src="imageUrl"
          alt="Picture of Me"
          :placeholder="[100, 100, 10]"
        />
        <div class="square" />
      </div>
    </div>
    <div class="horizon" />
    <div class="spotify">
      <NowSpotify />
      <TopSpotify />
    </div>
  </main>
</template>

<style lang="scss" scoped>
.container {
  display: flex;
  flex-direction: row;
  margin-top: 1rem;
  margin-bottom: 2rem;
  gap: 2rem;

  .paragraph {
    font-size: 1.2rem;
    margin-left: 15%;
    p {
      margin-bottom: 1rem;
    }
  }

  .image {
    margin-right: 20%;
    position: relative;
    img {
      margin-left: 2rem;
      margin-top: 3rem;
      width: 700px;
      height: auto;
    }

    .square {
      position: absolute;
      top: 0;
      left: 0;
      z-index: -1;
      height: 25vh;
      width: 15vw;
      background-color: var(--square);
    }
  }

  @include for-phone-only {
    flex-direction: column;
    margin-left: 5%;
    .paragraph {
      margin: auto 0;
      p {
        margin-right: 5%;
      }
    }
    .image {
      margin: -2rem 5% 2rem 0;
      img {
        width: 240px;
        min-width: 140px;
        padding-right: 2.5rem;
      }
      .square {
        height: 30vh;
        width: 60vw;
      }
    }
  }
}

.horizon {
  margin-top: -2rem;
  border-bottom: 1rem solid $mint;
  width: 80%;
  z-index: -1;
  margin-right: auto;
  @include slide-in-animation(200px, $direction: "horizontal", $duration: 0.5s);
}
.spotify {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  width: 60%;
  margin: 2rem 2rem;
  margin-left: 15%;
  @include for-phone-only {
    width: 95%;
    margin: 2rem 5%;
    gap: 1rem;
  }
}
</style>
